Create jahanbaev
Unvares/dreamport-webar_test_task pull request #3
Opened 2021-10-29 08:49 UTC by jahanbaev

jahanbaev  test task

2021-11-01 06:57 UTC, Unvares commented
Привет! Мне нужно твоё решение, а не билд. Отправишь?

2021-11-01 09:41 UTC, jahanbaev commented
да могу, сейчас

2021-11-01 09:54 UTC, jahanbaev commented
https://github.com/jahanbaev/dreamport-webar_test_task

вот здесь полная решения

2021-11-02 14:33 UTC, Unvares commented
В целом, приложение работает, но соответствует всем критериям тестового, что ни есть хорошо.
Как мы ещё можем подключить css-стили и js-скрипты, кроме как прямым добавлением в html-файл?

2021-11-02 14:33 UTC, Unvares requested changes

2021-11-02 14:33 UTC, Unvares commented on jahanbaev
> +function arst(){
Что это за переменные и для чего они используются?

2021-11-02 14:33 UTC, Unvares commented on jahanbaev
> +        >
По условию задачи нужно использовать pattern-маркер. Более того, на реальных проектах почти всегда используется именно он. Знаешь как его добавить?

2021-11-02 14:33 UTC, Unvares commented on jahanbaev
> +    <a-scene
Видеоролик должен воспроизводиться и ставиться на паузу по нажатию на него, а не на кнопку. Знаешь как это сделать?

2021-11-04 14:09 UTC, jahanbaev commented on jahanbaev
> +function arst(){
да могу но вы сказали что выбрали другой кандидат

2021-11-04 14:09 UTC, jahanbaev commented on jahanbaev
> +function arst(){
для привлечения кнопки

2021-11-04 14:10 UTC, jahanbaev commented on jahanbaev
> +        >
да знаю

2022-09-14 13:57 UTC, closed without merging